FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

COPY packages/shared ./shared
COPY services/ingestion/requirements.txt .
RUN pip install -r requirements.txt --target .

# Install Playwright browsers
RUN python -m playwright install chromium
RUN python -m playwright install-deps chromium

COPY services/ingestion/ .

CMD ["handler.handler"]